### ISSUE TITLE
Create OptiNiSt DFD

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#371]
- Purpose
  - Understanding optinist specifications (onboarding)
  - Development of optinist design documentation

- Anticipated Deliverables
  - Creation of DFD
  	- Identification of data types referenced by optinist
	- Classification by backend and frontend
	- Visualization of data flow for each function
	  - Workflow(snakemake), API, etc.

- Related
  - #370

**Comment by milesAraya** [comment]
Incomplete:
[React_dataFlow.pdf](https://github.com/user-attachments/files/16092213/React_dataFlow.pdf)

**Comment by milesAraya** [comment]
Freeform became too complicated. I worked with Claude on a Mermaid version. However, this also became difficult to read, so I am converting my Memaid code into a Drawio DFD because it is possible to manually move and edit boxes. 



![Image](https://github.com/arayabrain/barebone-studio/assets/171535965/69c65ae3-4479-46d7-90ab-aa13c25d570d)

**Comment by milesAraya** [comment]
Version 3

![Image](https://github.com/arayabrain/barebone-studio/assets/171535965/6f2475cb-d60a-4ce7-848e-5e704d2a3671)

**Comment by milesAraya** [comment]
Version 4: included User adding nodes, workspaces, experiments

![Image](https://github.com/arayabrain/barebone-studio/assets/171535965/47edd522-a9b6-4e10-af5c-e79b4af7fdc8)

**Comment by milesAraya** [comment]
New DFD is a joint project with Tsuchiyama-san. It will be updated as we update the existing code. 

https://drive.google.com/file/d/1bIprMadPHhrzEqbW-y8XnLuTKBAN97NS/view?usp=sharing

**Comment by itutu-tienday** [comment]
close as document v1 has been released.
