### ISSUE TITLE
Create Multiple Frontend Test

### ISSUE THREAD

**Issue by tsuchiyama-araya** [arayabrain/barebone-studio#443]
Create as many as I can frontend test.
The tests needed to be done are in the spreadsheet below.

https://docs.google.com/spreadsheets/d/1WdtZA0jXOrPrVQmtkEGkzk9erUV-aMRTgGA1cT7G7N4/edit?gid=1074153019#gid=1074153019

**Comment by itutu-tienday** [comment]
Testing the workflow screen has not been implemented yet due to compatibility issues between component (react flow) and jest.

### Solution
- [ ] Test implementation focused on Workflow state management
  -  The important point in testing the workflow screen is testing the workflow execution status, so we will consider a testing method that does not depend on react components.
  - Related
    - #302

**Comment by tsuchiyama-araya** [comment]
> Testing the workflow screen has not been implemented yet due to compatibility issues between component (react flow) and jest.
> 
> ### Solution
> * * [ ]  Test implementation focused on Workflow state management
>     
>     * The important point in testing the workflow screen is testing the workflow execution status, so we will consider a testing method that does not depend on react components.* Related
>       
>       * [異常停止したWorkflowの自動reloadの改善 #302](https://github.com/arayabrain/barebone-studio/issues/302)

こちらの件はまだ解決ではないですが、別のIssueに記載しました。
https://github.com/arayabrain/barebone-studio/issues/483
